FROM node:alpine

WORKDIR /app

COPY package.json /app

RUN npm cache clean --force

RUN npm install --no-package-lock

RUN npm install --save typescript@3.9.2 --no-package-lock

RUN npm install -g @angular/cli --no-package-lock


COPY . /app

CMD ["npm", "run", "start:dev"]