version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - acts
      - customers
      - gcustomers
      - labs

  envoy:
    image: envoyproxy/envoy-alpine:v1.15.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - test

  db_files:
    image: postgres
    volumes:
      - ./db_data/db_files2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6001:5432"
    networks:
      - files
  api_files:
    build:
      context: "./files"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./files:/app"
      - "/app/node_modules"
    networks:
      - files
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_files
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3010:3010"
      - "50051:50051"
    depends_on:
      - db_files
      - api_acts
    command: yarn start:dev

  api_subscriptions:
    build:
      context: "./api-subscriptions"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./api-subscriptions:/app"
      - "app/node_modules"
    networks:
      - files
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_files
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3060:3060"
    depends_on:
      - db_files

    command: yarn start:dev

  db_acts:
    image: postgres
    volumes:
      - ./db_data/db_acts2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6002:5432"
    networks:
      - acts
  api_acts:
    build:
      context: "./acts"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./acts:/app"
      - "app/node_modules"
    networks:
      - acts
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_acts
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3020:3020"
    depends_on:
      - db_acts
      - api_customers
    command: npm run start:dev

  db_customers:
    image: postgres
    volumes:
      - ./db_data/db_customers2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6003:5432"
    networks:
      - customers
  api_customers:
    build:
      context: "./customers"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./customers:/app"
      - "app/node_modules"
    networks:
      - customers
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_customers
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3030:3030"
    depends_on:
      - db_customers
      - api_general_customers
    command: npm run start:dev

  db_general_customers:
    image: postgres
    volumes:
      - ./db_data/db_general_customers:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6004:5432"
    networks:
      - gcustomers
  api_general_customers:
    build:
      context: "./general-customers"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./general-customers:/app"
      - "app/node_modules"
    networks:
      - test
      - gcustomers
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_general_customers
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3040:3040"
    depends_on:
      - db_general_customers
      - api_labs
    command: yarn start:dev

  db_labs:
    image: postgres
    volumes:
      - ./db_data/db_labs:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6005:5432"
    networks:
      - labs
  api_labs:
    build:
      context: "./labs"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./labs:/app"
      - "app/node_modules"
    networks:
      - labs
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_labs
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3050:3050"
    depends_on:
      - db_labs
    command: yarn start:dev

  db_tos:
    image: postgres
    volumes:
      - ./db_data/db_tos:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6009:5432"
    networks:
      - tos
  api_tos:
    build:
      context: "./type-of-sample"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./type-of-sample:/app"
      - "/app/node_modules"
    networks:
      - tos
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_tos
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3090:3090"
    depends_on:
      - db_labs
      - api_files
    command: yarn start:dev

  db_rules:
    image: postgres
    volumes:
      - ./db_data/db_rules:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mobicolab
      POSTGRES_USER: mobicolab
      POSTGRES_DB: postgres
    ports:
      - "6007:5432"
    networks:
      - rules
  api_rules:
    build:
      context: "./rules"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./rules:/app"
      - "/app/node_modules"
    networks:
      - rules
      - test
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_HOST_DOCKER: db_rules
      TYPEORM_USERNAME: mobicolab
      TYPEORM_PASSWORD: mobicolab
      TYPEORM_DATABASE: postgres
    ports:
      - "3070:3070"
    depends_on:
      - db_labs
      - api_tos
    command: yarn start:dev

  db_mongo:
    image: mark600/mobicolab_portal_db:latest
    volumes:
      - ./db_data/mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db_mongo
  server:
    build:
      context: "./server"
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - "./server:/app"
    networks:
      - test
      - db_mongo
    ports:
      - "3000:3000"
    depends_on:
      - db_mongo
    command: npm run dev

  web:
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    volumes:
      - "./client:/app"
      # - "/app/node_modules"
    ports:
      - "4200:4200"
    networks:
      - test
    depends_on:
      - api_files

  api_gateway:
    build:
      context: "./api-gateway"
      dockerfile: "Dockerfile.dev"
    restart: always
    volumes:
      - "./api-gateway:/app"
      - "/app/node_modules"
    networks:
      - test
    ports:
      - "2000:2000"
      - "50020:50020"
    command: yarn start:dev
    depends_on:
      - api_files
      - api_customers
      - api_general_customers
      - api_labs

  # api_bridge:
  #   build:
  #     context: './bridge'
  #     dockerfile: "Dockerfile.dev"
  #   restart: always
  #   volumes:
  #     - "./bridge:/usr/app"
  #     - '/usr/app/node_modules'
  #   networks:
  #     - test
  #   depends_on:
  #       - db
  #       - api_files
  # ports:
  #   - "5000:5000"
  # command: npm run start:dev

# volumes:
#   mongo-data:
networks:
  db_mongo:
  test:
  tos:
  rules:
  acts:
  customers:
  gcustomers:
  labs:
  files:
