apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: mark600/mobicolab_portal_client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js:"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.scss"
            dest: .
          - src: "**/*.html"
            dest: .
    - image: mark600/mobicolab_portal_api_acts
      context: acts
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
    - image: mark600/mobicolab_portal_api_customers
      context: customers
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
    - image: mark600/mobicolab_portal_api_general_customers
      context: general-customers
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
    - image: mark600/mobicolab_portal_api_labs
      context: labs
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
    # - image: mark600/mobicolab_portal_api_files
    #   context: files
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     manual:
    #       - src: "**/*.js"
    #         dest: .
    #       - src: "**/*.ts"
    #         dest: .
    - image: mark600/mobicolab_portal_api_subscriptions
      context: api-subscriptions
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
    - image: mark600/mobicolab_portal_api_gateway
      context: api-gateway
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - k8s/deployments/client-deployment.yaml
      - k8s/deployments/api-acts-deployment.yaml
      - k8s/deployments/api-customers-deployment.yaml
      - k8s/deployments/api-general-customers-deployment.yaml
      - k8s/deployments/api-labs-deployment.yaml
      # - k8s/deployments/api-files-deployment.yaml
      - k8s/deployments/api-subscriptions-deployment.yaml
      - k8s/deployments/api-gateway-deployment.yaml
      - k8s/services/client-cluster-ip-service.yaml
      - k8s/services/api-acts-cluster-ip-service.yaml
      - k8s/services/api-customers-cluster-ip-service.yaml
      - k8s/services/api-general-customers-cluster-ip-service.yaml
      - k8s/services/api-labs-cluster-ip-service.yaml
      - k8s/services/api-files-cluster-ip-service.yaml
      - k8s/services/api-subscriptions-cluster-ip-service.yaml
      - k8s/services/api-gateway-cluster-ip-service.yaml
