apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-acts-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: api-acts
    template:
        metadata:
            labels:
                component: api-acts
        spec:
            volumes:
                - name: db-storage
                  persistentVolumeClaim:
                      claimName: database-persistent-volume-claim
            containers:
                - name: api-acts
                  image: mark600/mobicolab_portal_api_acts
                  env:
                      - name: TYPEORM_HOST_DOCKER
                        value: db-acts
                  envFrom:
                      - configMapRef:
                        name: typeorm-config-general
                  ports:
                      - containerPort: 3020
                - name: db-acts
                  image: postgres
                  envFrom:
                      - configMapRef:
                        name: postgres-config-general
                  volumeMounts:
                      - name: db-storage
                        mountPath: /var/lib/postgresql/data
                        subPath: postgres
                  ports:
                      - containerPort: 5432
