apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-files
---
apiVersion: v1
kind: Service
metadata:
  name: db-files-svc
  labels:
    app: db-files
spec:
  type: ClusterIP
  selector:
    app: db-files
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-files
  template:
    metadata:
      labels:
        app: db-files
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: db-files
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config-general
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgres/data
              subPath: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "200Mi"
