apiVersion: v1
kind: Service
metadata:
  name: db-general-customers-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: db-general-customers
  ports:
    - port: 5432
      targetPort: 5432