apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-labs-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: db-labs
  template:
    metadata:
      labels:
        component: db-labs
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: db-labs
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config-general
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          ports:
            - containerPort: 5432