apiVersion: apps/v1
kind: Deploymnet
metadata:
  name: api-files-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-files
  template:
    metadata:
      labels:
        component: api-files
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
        - name: api-files
          image: mark600/mobicolab_portal_api_files
          env:
            - name: TYPEORM_HOST_DOCKER
              value: db-files
          envFrom:
            - configMapRef:
                name: typeorm-config-general
          ports:
            - containerPort: 3010
        - name: db-files
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config-general
          volumeMounts:
            - name: db-storage
              mountPaht: /var/lib/postgres/data
              subPath: postgres
          ports:
            - containerPort: 5432