apiVersion: v1
kind: Service
metadata:
  name: api-subscriptions-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api-subscriptions
  ports:
    - port: 3060
      name: api
      targetPort: 3060