apiVersion: v1
kind: Service
metadata:
  name: api-general-customers-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api-general-customers
  ports:
    - port: 3040
      name: api
      targetPort: 3040
    - port: 6040
      name: db
      targetPort: 6040