apiVersion: v1
kind: Service
metadata:
  name: api-labs-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: api-labs
  ports:
    - port: 3050
      targetPort: 3050
    - port: 6050
      targetPort: 5432