apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-subscriptions-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-subscriptions
  template:
    metadata:
      labels:
        component: api-subscriptions
    spec:
      containers:
        - name: api-subscriptions
          image: mark600/mobicolab_portal_api_subscriptions
          env:
            - name: TYPEORM_HOST_DOCKER
              value: db-subscriptions
          envFrom:
            - configMapRef:
                name: typeorm-config-general
          ports:
            - containerPort: 3060
        