apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-acts-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api-acts
    template:
        metadata:
            labels:
                component: api-acts
        spec:
            containers:
                - name: api-acts
                  image: mark600/mobicolab_portal_api_acts
                  env:
                      - name: TYPEORM_HOST_DOCKER
                        value: db-acts-cluster-ip-service
                  envFrom:
                      - configMapRef:
                            name: typeorm-config-general
                  ports:
                      - containerPort: 3020
