apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-general-customers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      compnent: api-general-customers
  template:
    metadata:
      labels:
        compnent: api-general-customers
    spec:
      containers:
        - name: api-general-customers
          image: mark600/mobicolab_portal_api_general_customers
          env:
            - name: TYPEORM_HOST_DOCKER
              value: db-general-customers-cluster-ip-service
          envFrom:
            - configMapRef:
                name: typeorm-config-general
          ports:
            - containerPort: 3040