apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-labs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api-labs
  template: 
    metadata:
      labels:
        component: api-labs
    spec:
      containers:
        - name: api-labs
          image: mark600/mobicolab_portal_api_labs
          env:
            - name: TYPEORM_HOST_DOCKER
              value: db-labs
          envFrom:
            - configMapRef:
                name: typeorm-config-general
          ports:
            - containerPort: 3050